apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sockshop
spec:
  hosts:
  - "*"
  gateways:
  - sockshop-gateway
  http:
  - match:
    - headers:
        user-agent:
          regex: ".*Chrome.*"
    route:
    - destination:
        host: front-end.production.svc.cluster.local
        subset: v2
  - route:
    - destination:
        host: front-end.production.svc.cluster.local
        subset: v1
