apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-pluginservice
  namespace: easytravel
spec:
  selector:
    matchLabels:
      app: easytravel-pluginservice
  replicas: 1
  template:
    metadata:
      labels:
        app: easytravel-pluginservice
      annotations:
        support.contact: "demoability@dynatrace.com"
        support.channel: "#team-demoability"
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=APM -Djava.security.egd=file:/dev/./urandom
        image: robjahn/easytravel-pluginservice:k8s
        imagePullPolicy: "Always"
        name: easytravel-pluginservice
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /PluginService/ping
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
