---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-db-mongodata
  namespace: sockshop-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  namespace: sockshop-dev
spec:
  selector:
    matchLabels:
      name: carts-db
      stage: dev
      version: "1.3"
      tier: data
      product: sockshop
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/port: '9216'
        pipeline.stage: dev
        pipeline.build: 1.3.0.5464
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        name: carts-db
        stage: dev
        version: "1.3"
        tier: data
        product: sockshop
    spec:
      containers:
      - image: mongo
        name: carts-db
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: "password"
        - name: MONGODB_USER
          value: "user"
        - name: MONGODB_PASSWORD
          value: "password"
        - name: MONGODB_DATABASE
          value: "carts-db"
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: carts-db-mongodata
      - image: ssheehy/mongodb-exporter:0.10.0
        name: exporter
        args:
          - --web.listen-address=:9216
          - --collect.collection
          - --collect.database
          - --collect.indexusage
          - --collect.topmetrics
          - --collect.connpoolstats
        env:
        - name: MONGODB_URI
          value: mongodb://localhost:27017
      restartPolicy: Always
      volumes:
      - name: carts-db-mongodata
        persistentVolumeClaim:
          claimName: carts-db-mongodata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  namespace: sockshop-production
spec:
  selector:
    matchLabels:
      name: carts-db
      stage: prod
      release: stable
      version: "1.2"
      tier: data
      product: sockshop
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/port: '9216'
        pipeline.stage: prod-stable
        pipeline.build: 1.2.0.2644
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        name: carts-db
        stage: prod
        release: stable
        version: "1.2"
        tier: data
        product: sockshop
    spec:
      containers:
      - image: mongo
        name: carts-db
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: "password"
        - name: MONGODB_USER
          value: "user"
        - name: MONGODB_PASSWORD
          value: "password"
        - name: MONGODB_DATABASE
          value: "carts-db"
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: carts-db-mongodata
      - image: ssheehy/mongodb-exporter:0.10.0
        name: exporter
        args:
          - --web.listen-address=:9216
          - --collect.collection
          - --collect.database
          - --collect.indexusage
          - --collect.topmetrics
          - --collect.connpoolstats
        env:
        - name: MONGODB_URI
          value: mongodb://localhost:27017
      restartPolicy: Always
      volumes:
      - name: carts-db-mongodata
        persistentVolumeClaim:
          claimName: carts-db-mongodata

