apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sockshop
  namespace: sockshop-production
spec:
  hosts:
  - "*"
  gateways:
  - sockshop-gateway
  http:
  - match:
    - uri:
        prefix: "/carts"
    route:
    - destination:
        host: carts
  - match:
    - uri:
        prefix: "/login"
    route:
    - destination:
        host: front-end
        subset: v1
  - match:
    - headers:
        cookie:
          regex: ".*logged_in.*"
    route:
    - destination:
        host: front-end
        subset: v1
  - route:
    - destination:
        host: front-end
        subset: v2